- name: Diskgroup check
  shell: "{{ oracle_home_gi }}/bin/srvctl status diskgroup -g {{ item.diskgroup }}"
  with_items: "{{asm_diskgroups}}"
  when:  asm_diskgroups is defined
  tags: listgroup
  register: listgroup
  environment: "{{ oracle_env }}"
  failed_when: "'does not exist' in listgroup.stdout"

- name: Dismount ASM diskgroup
  shell: srvctl stop diskgroup -diskgroup {{ item.diskgroup }} -n {{ racnodes }}
  with_items: "{{asm_diskgroups}}"
  when: drop_diskgroup and not drop_disk and is_rac
  environment: "{{ oracle_env }}"
  register: dismountgroup
  ignore_errors: True

- name: Drop ASM diskgroup
  shell: echo "drop diskgroup {{ item.diskgroup }} including contents;" | sqlplus / as sysasm
  with_items: "{{asm_diskgroups}}"
  when: drop_diskgroup and not drop_disk
  environment: "{{ oracle_env }}"
  register: dropgroup

- name: Drop ASM Disk
  shell: echo "alter diskgroup {{ item.diskgroup }} drop disk {{ item.disk }};" | sqlplus / as sysasm
  with_items: "{{asm_diskgroups}}"
  when: drop_disk and not drop_diskgroup
  environment: "{{ oracle_env }}"
  register: dropdisk
