- name: oradb-datapatch | Start listener
  shell: "export PATH=${ORACLE_HOME}/bin:${PATH}; lsnrctl start {{ lsnrinst.listener_name }} /dev/null; exit 0"
  environment: "{{ oracle_env_lsnrctl }}"
  become_user: "{{ oracle_user }}"
  with_items: "{{ listener_installed }}"
  loop_control:
     loop_var: lsnrinst
     label: "LISTENER: {{ lsnrinst.listener_name }} ORACLE_HOME: {{ listener_home }}"
  when: listener_installed is defined and lsnrinst.state|lower == 'present'

- name: oradb-datapatch | Start database
  environment: "{{ oracle_env }}"
  shell: "export PATH=${ORACLE_HOME}/bin:${PATH}; echo 'startup' | sqlplus -S '/ as sysdba'"
  tags: startdb
  register: startdb

- name: oradb-datapatch | Run datapatch
  environment: "{{ oracle_env }}"
  shell: "{{ oracle_db_home }}/OPatch/datapatch -verbose"
  tags: datapatch
  register: datapatch

- debug:
    var: datapatch
