---
#Instructions to set AWR retention using this file.
#Playbook: ansible_oracle_aix/awr-task.yml
#This is a standalone task. Set the variables in the file itself.
#Modify the variables under "vars" section. Do NOT change other sections of this file.

#hostname = AIX lpar hostname
#service_name = Database service name in which we're setting AWR retention policy.
#db_password_cdb = Sys user password
#listener_port = Listener
#interval = Snapshot interval in minutes. To disable set the value to 0.
#retention = Snapshot Retention period (in days)
#ORACLE_HOME = Oracle Home location of Oracle client installed on Ansible host.
#LD_LIBRARY_PATH = Oracle Libraries location of Oracle client installed on Ansible host.

#Execute this playbook
#ansible-playbook ansible_oracle_aix/awr-task.yml

- hosts: localhost
  connection: local
  vars:

     name: Global Variables
     hostname: ansible_db               # AIX hostname.
     service_name: ansible.pbm.ihost.com        # DB service name.
     db_user: sys
     db_password_cdb: oracle            # Sys user password.
     listener_port: 1521                # DB port number.
     db_mode: sysdba
     interval: 30               # Snapshot interval (in minutes). '0' disables.
     retention: 15              # Snapshot Retention period (in days)
     oracle_env:
       ORACLE_HOME: /home/ansible/oracle_client
       LD_LIBRARY_PATH: /home/ansible/oracle_client/lib

  tasks:

   - name: Modify AWR settings
     oracle_awr:
       hostname: "{{ hostname }}"
       service_name: "{{ service_name }}"
       port: "{{ listener_port }}"
       user: "{{ db_user }}"
       password: "{{ db_password_cdb }}"
       mode: "{{ db_mode }}"
       snapshot_interval_min: "{{ interval }}"
       snapshot_retention_days: "{{ retention }}"
     environment: "{{ oracle_env }}"
     register: awr
   - debug:
       var: awr
