---
- hosts: localhost
  connection: local
  vars:
     hostname: ansible_db                               # AIX Hostname.
     service_name: db122c                               # Service name of a PDB or CDB.
     db_user: sys
     db_password_cdb: oracle                            # SYS user password.
     listener_port: 1521                                # DB listener port.
     db_mode: sysdba                                    
     oracle_env:
       ORACLE_HOME: /home/ansible/oracle_client         # Oracle client s/w path on Ansible controller.
       LD_LIBRARY_PATH: /home/ansible/oracle_client/lib # Oracle client library path on Ansible controller.

  tasks:
   - name: gather database facts
     oracle_facts:
       hostname: "{{ hostname }}"
       port: "{{ listener_port }}"
       service_name: "{{ service_name }}"
       user: "{{ db_user }}"
       password: "{{ db_password_cdb }}"
       mode: "{{ db_mode }}"
     environment: "{{ oracle_env }}"
     register: dbfacts
   - debug:
       var: dbfacts
