namespace: "ibm"

name: "power_aix_oracle_dba"

version: 1.0.0

readme: "README.md"

authors:
- "Shiva Laveti <shiva.laveti@ibm.com>"

license_file:
- "LICENSE"
- "NOTICE"

tags:
- power
- aix
- ibm

dependencies: {}

repository: "https://github.com/IBM/ansible-power-aix-oracle-dba"

documentation: "https://github.com/IBM/ansible-power-aix-oracle-dba"

homepage: "https://github.com/IBM/ansible-power-aix-oracle-dba"

issues: "https://github.com/IBM/ansible-power-aix-oracle-dba/issues"
