---

#Readme for global statistics

#Playbook: ansible_oracle_aix/globalstats-task.yml
#This is a standalone task. Set the variables in the file itself.
#Modify the variables under "vars" section. Do NOT change other sections of the file.

#hostname = AIX lpar hostname
#service_name = Database service name in which we're setting AWR retention policy.
#db_password_cdb = Sys user password
#listener_port = Listener

#preference_name: Statistics preference
#preference_value: Statistics value
#state: present/absent
#ORACLE_HOME = Oracle Home location of Oracle client installed on Ansible host.
#LD_LIBRARY_PATH = Oracle Libraries location of Oracle client installed on Ansible host.


- hosts: localhost
  connection: local
  vars:

     name: Global Variables
     hostname: ansible_db
     service_name: db122c
     db_user: sys
     db_password_cdb: oracle
     listener_port: 1521
     db_mode: sysdba
     preference_name: CONCURRENT
     preference_value: ALL
     state: present
     oracle_env:
       ORACLE_HOME: /home/ansible/oracle_client
       LD_LIBRARY_PATH: /home/ansible/oracle_client/lib

  tasks:

   - name: Manage Global preferences
     oracle_stats_prefs:
       hostname: "{{ hostname }}"
       service_name: "{{ service_name }}"
       port: "{{ listener_port }}"
       user: "{{ db_user }}"
       password: "{{ db_password_cdb }}"
       mode: "{{ db_mode }}"
       preference_name: "{{ preference_name }}"
       preference_value: "{{ preference_value }}"
       state: "{{ state }}"
     environment: "{{ oracle_env }}"
     register: stats
   - debug:
       var: stats
