---
- hosts: localhost
  connection: local

  vars:     
     name: Global Variables
     hostname: ansible_db               # AIX hostname.
     service_name: db122c               # DB service name.
     db_user: sys
     db_password_cdb: oracle            # Sys user password.
     listener_port: 1521                # DB port number.
     db_mode: sysdba
     param_name: log_archive_dest_state_2       # Initialization Parameter Name
     param_value: defer                         # Initialization Parameter Value
     state: present                              # Initialization Parameter state: present - sets the value, absent/reset - disables the parameter
     oracle_env:
       ORACLE_HOME: /home/ansible/oracle_client         # Oracle client s/w path on Ansible controller.
       LD_LIBRARY_PATH: /home/ansible/oracle_client/lib # Oracle client library path on Ansible controller.

  tasks:
    - oracle_parameter:
            hostname: "{{ hostname }}"
            service_name: "{{ service_name }}"
            port: "{{ listener_port }}"
            user: "{{ db_user }}"
            password: "{{ db_password_cdb }}"
            mode: "{{ db_mode }}"
            name: "{{ param_name }}"
            value: "{{ param_value }}"
            state: "{{ state }}"
      environment: "{{ oracle_env }}"
      register: parameter

    - debug: 
        var: parameter
