---
- hosts: localhost
  connection: local
  vars:

     name: Global Variables
     hostname: ansible_db
     service_name: db122cpdb
     db_user: sys
     db_password_cdb: oracle
     listener_port: 1521
     db_mode: sysdba
     state: present
     consumer_group: ansigroup1
     comments:  This is a test consumer resource group
     grant: 
        - ANSIUSER1
     map_oracle_user: 
        - ANSIUSER1
     map_service_name:
        - db122cpdb
     map_client_machine:
        - x134vm236
     oracle_env:
       ORACLE_HOME: /home/ansible/oracle_client
       LD_LIBRARY_PATH: /home/ansible/oracle_client/lib

  tasks:

   - name: Resource Consumer Groups
     oracle_rsrc_consgroup:
       hostname: "{{ hostname }}"
       service_name: "{{ service_name }}"
       port: "{{ listener_port }}"
       user: "{{ db_user }}"
       password: "{{ db_password_cdb }}"
       mode: "{{ db_mode }}"
       name: ansigroup1
       state: "{{ state }}"
       comments: This is a test consumer resource group
       grant: "{{ grant }}"
       map_oracle_user: "{{ map_oracle_user }}"
       map_service_name: "{{ map_service_name }}"
       map_client_machine: "{{ map_client_machine }}"
     environment: "{{ oracle_env }}"
     register: rsc
   - debug:
       var: rsc
