---

  - name: ASMCA | Create script to build asm-diskgroups
    template: src=asmca-diskadd-aix.sh.j2 dest="{{ oracle_rsp_stage }}/asmca-diskadd-{{ item.diskgroup }}.sh"  owner="{{ grid_install_user }}" group={{ oracle_group }} mode=744 backup=yes
    with_items: "{{asm_diskgroups}}"
    when: asm_diskgroups is defined
    tags: asmcaa

  - name: ASMCA | Add ASM disks
    shell: "{{ oracle_rsp_stage }}/asmca-diskadd-{{ item.diskgroup }}.sh"
    with_items: "{{asm_diskgroups}}"
    become: yes
    become_user: "{{ grid_install_user }}"
    when: asm_diskgroups is defined
    ignore_errors: True
    tags: asmca
    register: asmca

  - name: Print Results
    debug: var=item
    with_items:
       - "{{ asmca.results|map(attribute='stdout_lines')|list }}"
    ignore_errors: true
    tags: asmca
