  hostgroup: "{{ group_names[0] }}"
  oracle_dbca_rsp: "dbca_{{ oracle_db_name }}.rsp"        # Name of responsefile used by dbca. One per database
  oracle_netca_rsp: "netca_{{ item.home }}_{{ listener_name_template }}.rsp"
  oracle_user: oracle             # User that will own the Oracle Installations.
  oracle_user_home: "/home/{{ oracle_user }}" # Home directory for oracle_user. Needed for passing in ssh-keys, profiles etc
  oracle_group: oinstall    # Primary group for oracle_user.

  oracle_home_db: "{{% if oracle_home is defined %}{{ oracle_home}}{% else %}{{ oracle_base }}/{{ oracle_version_db }}/{{ home }}{% endif %}}"

  oracle_stage: /tmp # Location on the target AIX lpar to stage response files. 
  oracle_rsp_stage: "{{ oracle_stage }}/rsp"
  oracle_inventory_loc: /u01/app/oraInventory
  oracle_base: /u01/app/oracle
  oracle_profile_name: ".profile_{{ item.oracle_db_name }}"       # Name of profile-file. Sets up the environment for that database. One per database
  oracle_dbf_dir_fs: /oradata                              # If storage_type=FS this is where the database is placed.
  oracle_reco_dir_fs: /oradata                             # If storage_type=FS this is where the fast recovery area is placed.
  oracle_dbf_dir_asm: '+DATA1'                                    # If storage_type=ASM this is where the database is placed.
  oracle_reco_dir_asm: '+DATA1'                                   # If storage_type=ASM this is where the fast recovery area is placed
  datafile_dest: "{% if storage_type|upper == 'FS' %}{{ oracle_dbf_dir_fs }}{% elif storage_type|upper == 'ASM' %}{{ oracle_dbf_dir_asm }}{% else %}{% endif %}"
  recoveryfile_dest: "{% if storage_type|upper == 'FS' %}{{ oracle_reco_dir_fs }}{% elif storage_type|upper == 'ASM' %}{{ oracle_reco_dir_asm }}{% else %}{% endif %}"
  configure_cluster: False   # Set it true when creating RAC database
  oracle_install_option_gi: "none"
  oracle_gi_cluster_type: STANDARD
  hostgroup_hub: "{{ hostgroup }}-hub"
  hostgroup_leaf: "{{ hostgroup }}-leaf"
  create_listener: "{% if oracle_install_option_gi is defined %}False{% elif oracle_install_option_gi is undefined %}{% if item.listener_name is defined %}True{% else %}False{% endif %}{% endif %}"
  listener_name_template: "{% if item.listener_name is defined %}{{ item.listener_name }}{% else %}{{ listener_name }}{% endif %}"
  listener_protocols_template: "{% if item.listener_protocols is defined %}{{ item.listener_protocols }}{% else %}{{ listener_protocols }}{% endif %}"
  listener_port_template: "{% if item.listener_port is defined %}{{ item.listener_port }}{% else %}{{ listener_port }}{% endif %}"
  listener_name: ANSILIST
  listener_protocols: TCP
  listener_port: 1521
  autostartup_service: false

# Everything between the lines START-OF-PASSWORDS & END-OF-PASSWORDS can be
# put in an external passwords.yml file and be encrypted by Vault.
# The file should be put in 'group_vars/<your-config>/passwords.yml'
# This example will be broken out to a passwords.yml as soon as is allowed in ansible

  dbca_templatename: General_Purpose.dbc
  dbca_initParams: "{% if '19.3' in item.0.oracle_version_db %} -initParams db_name={{item.0.oracle_db_name}}{% if item.0.oracle_db_unique_name is defined %},db_unique_name={{item.0.oracle_db_unique_name}}{% endif %}{% endif %}"

# This is an example layout of a database installation
#  oracle_databases:                                             # Dictionary describing the databases to be installed
#        - home: dbhome_1                                             # 'Last' directory in ORACLE_HOME path (e.g /u01/app/oracle/12.1.0.2/racdb)
  home: dbhome_1                                             # 'Last' directory in ORACLE_HOME path (e.g /u01/app/oracle/12.1.0.2/racdb)
  oracle_version_db: 19.3.0.0                   # Oracle version
  oracle_home: /u01/app/oracle/product/19.0.3/dbhome_1            # Oracle Home location.
  oracle_edition: EE                                    # The edition of database-server (EE,SE,SEONE)
  oracle_db_name: testdb1                                 # Database name
  oracle_db_type: SI                                   # Type of database (RAC,RACONENODE,SI)
  is_container: True                                    # (true/false) Is the database a container database
  pdb_prefix: devpdb # Pluggable database name.
  num_pdbs: 1 # Number of pluggable databases.
  storage_type: FS                                     # Database storage to be used. ASM or FS.
  service_name: "{{oracle_db_name}}"                                   # Inital service to be created.
  oracle_init_params: ""                                # Specific parameters to be set during installation. Comma-separated list
  oracle_db_mem_totalmb: 10000                          # Amount of RAM to be used for SGA + PGA
  oracle_database_type: MULTIPURPOSE                    # MULTIPURPOSE|DATA_WAREHOUSING|OLTP
  redolog_size_in_mb: 50 # Redolog size in MB
  state: present                                        # present | absent
