- oracle_sql:
    username: "{{ user }}"
    password: "{{ password }}"
    service_name: "{{ service_name }}"
    hostname: "{{ hostname }}"
    port: "{{ listener_port }}"
    mode: "{{ db_mode }}"
    script: "{{ item.script }}"
  with_items:
    - "{{ sqlfile }}"
  environment: "{{ oracle_env }}"
  register: output
- debug:
    var: output
