# This playbook executes "oraswdb_manage_patches" role. Opatchauto option must be set in the variables file & opatchauto must be disabled in order to avoid conflict.
# Make sure to set the variables appropriately to avoid failure(s) or patching of unintended instances.
# Make sure to setup passwordless ssh between the Ansible conrtoller user & Oracle Home user on the AIX lpar.
# 
# Variables file path: power_aix_oracle_dba/roles/oraswdb_manage_patches/defaults/main.yml

- name: Apply binary patches
  gather_facts: yes
  hosts: rachosts     # AIX lpar RAC host group names, make sure it's set in the inventory.
  remote_user: oracle   # AIX lpar Oracle home user.
  serial: 1
  roles:
     - {role: oraswdb_manage_patches }
