- hosts: 	D-LLOY-oracle1
  connection: local
  pre_tasks:
   - name: include variables
     include_vars:
       dir: vars
       extensions:
         - 'yml'
  roles:
     - { role: oradb_gather_dbfacts_si }
