# Playbook to create redo log groups. Supports ASM file system only. Local Non-ASM file system is not supported.
- hosts: localhost
  connection: local
  pre_tasks:
   - name: include variables
     include_vars:
       dir: vars
       extensions:
         - 'yml'
  roles:
     - { role: oradb_manage_redo }
