# Playbook to create redo log groups. Supports ASM file system only. Local Non-ASM file system is not supported.
- hosts: localhost
  connection: local
  roles:
     - { role: ibm.ansible_power_aix_oracle_dba.oradb_manage_redo }
