- hosts: ansible_db                        # Provide the name of the target lpar registered in ansible_inventory.
  remote_user: root                     # This needs to be run by "root" user.
  gather_facts: False
  vars_files:
      - vars/upgrade/si_upgrade_vars.yml
      - vars/vault.yml
  roles:
     - role: si_has_upgrade
       tags: si_has_upgrade
     - role: oracle_install
       tags: oracle_install
     - role: db_upgrade
