hostname: ansible_db            # Target LPAR hostname
db_user: sys
listener_port: 1521             # Target DB listener port number
service_name: ansipdb.pbm.ihost.com     # Pluggable DB Service Name.
db_password_cdb: "{% if dbpasswords is defined and dbpasswords[item[1].cdb] is defined and dbpasswords[item[1].cdb][db_user] is defined%}{{dbpasswords[item[1].cdb][db_user]}}{% else %}{{ default_dbpass}}{% endif%}"
db_password_pdb: "{% if dbpasswords is defined and dbpasswords[item[1].cdb] is defined and dbpasswords[item[1].cdb][db_user] is defined%}{{dbpasswords[item[1].cdb][db_user]}}{% else %}{{ default_dbpass}}{% endif%}"
db_mode: sysdba
state: present                  # State: Present/Absent
consumer_group: ansigroup1      # Desired consumer group name
comments:  This is a test consumer resource group       # Optional
grant:
   - ANSIUSER1                  # Name of the user to provide grants to resource group.
map_oracle_user:
   - ANSIUSER1                  # Map user
map_service_name:
   - db122cpdb                  # Map service
map_client_machine:
   - x134vm236                  # Map client
oracle_env:
  ORACLE_HOME: /home/ansible/oracle_client              # Oracle client s/w location on the ansible controller.
  LD_LIBRARY_PATH: /home/ansible/oracle_client/lib      # Oracle client s/w library location on the ansible controller.
